# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b49f3c84ca269bfc605d2064dad561cb179a5a33059b3eb199856be1a9f56e11d325b1956842c2928832c9cb83c2ff8330613b2b7ac93dec71cdc4a40f69f1b

test:
  secret_key_base: 18f65ea86c9b700eeb96bc949f7239f26e24f8316c971e3e889f8a1d841a91b82cdccd8bf77323769edffa3b9c385f345d76d59558c3eb5560c2694e3c77404e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
